name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: none
          extensions: mbstring, intl, zip, dom, curl, sqlite3, pdo_sqlite

      - name: Configure Composer allow-plugins
        run: |
          composer config --no-plugins allow-plugins.composer/installers true
          composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer config --no-plugins allow-plugins.johnpbloch/wordpress-core-installer true

      - name: Get Composer cache dir
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install deps
        run: composer install --no-interaction --prefer-dist --no-progress

      # ──────────────────────────────────────────────────────────────────────
      # WordPress を ./wordpress に“必ず”用意（存在すれば触らない → 導入 → ベンダからリンク/コピー）
      # その上で ABSPATH=./wordpress の wp-tests-config.php を生成
      # ──────────────────────────────────────────────────────────────────────
      - name: Prepare WordPress core & wp-tests-config.php
        run: |
          set -e

          # 1) 既に ./wordpress が正しくあるなら何もしない
          if [ -f wordpress/wp-settings.php ]; then
            echo "Core already present at ./wordpress"
          else
            # 2) johnpbloch/wordpress (meta) を優先導入 → これが入ると ./wordpress に展開される
            echo "Ensuring WordPress core via johnpbloch/wordpress..."
            composer require johnpbloch/wordpress:^6.8 --no-interaction --prefer-dist || true

            if [ -f wordpress/wp-settings.php ]; then
              echo "WordPress installed at ./wordpress"
            else
              # 3) ベンダ配下の候補を探索して ./wordpress を作る（symlink優先→失敗時copy）
              for d in \
                vendor/johnpbloch/wordpress-core/wordpress \
                vendor/johnpbloch/wordpress \
                vendor/wordpress/wordpress
              do
                if [ -f "$d/wp-settings.php" ]; then
                  echo "Using vendor source: $d"
                  # 既に wordpress が中途半端なら消す（存在しなければ問題なし）
                  [ -e wordpress ] && rm -rf wordpress || true
                  ln -s "$PWD/$d" wordpress || (rm -rf wordpress && cp -a "$d" wordpress)
                  break
                fi
              done
            fi
          fi

          # 4) 最終確認（ここで必ず存在）
          if [ ! -f wordpress/wp-settings.php ]; then
            echo "FATAL: wordpress/wp-settings.php not found after install/prepare"
            ls -la || true
            exit 1
          fi

          # 5) ABSPATH=./wordpress で wp-tests-config.php を生成
          php -r '
            $root  = getenv("GITHUB_WORKSPACE") ?: __DIR__;
            $wpdir = $root . "/wordpress/";
            $cfg = "<?php\n"
              ."if(!defined(\"ABSPATH\"))define(\"ABSPATH\",\"".$wpdir."\");\n"
              ."if(!defined(\"WP_CONTENT_DIR\"))define(\"WP_CONTENT_DIR\",ABSPATH.\"wp-content\");\n"
              ."if(!defined(\"WP_TESTS_DOMAIN\"))define(\"WP_TESTS_DOMAIN\",\"example.org\");\n"
              ."if(!defined(\"WP_TESTS_EMAIL\"))define(\"WP_TESTS_EMAIL\",\"admin@example.org\");\n"
              ."if(!defined(\"WP_TESTS_TITLE\"))define(\"WP_TESTS_TITLE\",\"Test Site\");\n"
              ."if(!defined(\"WP_PHP_BINARY\"))define(\"WP_PHP_BINARY\",\"php\");\n"
              ."define(\"DB_NAME\",\"wptests\");\n"
              ."define(\"DB_USER\",\"root\");\n"
              ."define(\"DB_PASSWORD\",\"\");\n"
              ."define(\"DB_HOST\",\"localhost\");\n"
              ."define(\"DB_CHARSET\",\"utf8\");\n"
              ."define(\"DB_COLLATE\",\"\");\n"
              ."\$table_prefix=\"wptests_\";\n";
            file_put_contents($root . "/wp-tests-config.php", $cfg);
          '
          echo "Prepared ./wordpress and wp-tests-config.php"

      # tests/phpunit/bootstrap.php が無い場合のフォールバック
      - name: Ensure tests/phpunit/bootstrap.php (fallback)
        run: |
          set -e
          if [ -f tests/phpunit/bootstrap.php ]; then
            echo "bootstrap.php exists"
            exit 0
          fi
          mkdir -p tests/phpunit
          cat > tests/phpunit/bootstrap.php <<'PHP'
          <?php
          $_tests_dir = getenv('WP_PHPUNIT__DIR');
          if (! $_tests_dir || ! file_exists($_tests_dir . '/includes/bootstrap.php')) {
            fwrite(STDERR, "WP_PHPUNIT__DIR invalid\n");
            exit(1);
          }
          require $_tests_dir . '/includes/functions.php';
          tests_add_filter('muplugins_loaded', static function () {
            require_once dirname(__DIR__, 2) . '/test-plugin.php';
          });
          require $_tests_dir . '/includes/bootstrap.php';
          PHP
          echo "Wrote tests/phpunit/bootstrap.php"

      # SQLite ドロップインを ./wordpress/wp-content に配置（あれば）
      - name: Ensure SQLite drop-in
        run: |
          set -e
          mkdir -p wordpress/wp-content
          if [ -f vendor/aaemnnosttv/wp-sqlite-db/src/db.php ]; then
            cp -f vendor/aaemnnosttv/wp-sqlite-db/src/db.php wordpress/wp-content/db.php
            echo "Copied SQLite drop-in to wordpress/wp-content/db.php"
          else
            echo "aaemnnosttv/wp-sqlite-db not present; skipping copy"
          fi
          mkdir -p tmp && chmod -R 777 tmp

      - name: PHPCS
        run: |
          if [ -x vendor/bin/phpcs ]; then
            set -e
            paths=""
            for d in includes src lib app; do [ -d "$d" ] && paths="$paths $d"; done
            shopt -s nullglob; for f in *.php; do [ "$f" != "wp-tests-config.php" ] && paths="$paths $f"; done
            if [ -z "$(echo "$paths" | tr -d " ")" ]; then echo "No PHP sources to sniff; skipping"; exit 0; fi
            vendor/bin/phpcs \
              --standard=WordPress-Extra \
              --extensions=php \
              --ignore=vendor/*,tests/*,tests/wordpress/*,tmp/*,.github/*,node_modules/*,wp-content/*,wordpress/* \
              --warning-severity=0 \
              $paths
          else
            echo "phpcs not installed; skipping"
          fi

      - name: PHPStan
        run: |
          if [ -x vendor/bin/phpstan ]; then
            vendor/bin/phpstan analyse -c phpstan.neon
          else
            echo "phpstan not installed; skipping"
          fi

      - name: PHPUnit
        env:
          WP_PHPUNIT__DIR: ${{ github.workspace }}/vendor/wp-phpunit/wp-phpunit
          WP_PHPUNIT__TESTS_CONFIG: ${{ github.workspace }}/wp-tests-config.php
          WP_PHP_BINARY: php
        run: vendor/bin/phpunit -c phpunit.xml.dist
