name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: none
          extensions: mbstring, intl, zip, dom, curl, sqlite3, pdo_sqlite

      - name: Configure Composer allow-plugins
        run: |
          composer config --no-plugins allow-plugins.composer/installers true
          composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer config --no-plugins allow-plugins.johnpbloch/wordpress-core-installer true

      - name: Get Composer cache dir
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install deps
        run: composer install --no-interaction --prefer-dist --no-progress

      # WordPress コアを複数の可能性から検出して wp-tests-config.php を生成
      - name: Ensure wp-tests-config.php
        run: |
          set -e
          php -r '
            $root = getenv("GITHUB_WORKSPACE") ?: __DIR__;
            $cands = [
              $root."/wordpress/",
              $root."/wp/",
              $root."/vendor/johnpbloch/wordpress-core/wordpress/",
              $root."/vendor/johnpbloch/wordpress-core/",
              $root."/vendor/johnpbloch/wordpress/",
              $root."/vendor/wordpress/wordpress/",
            ];
            $found = null;
            foreach ($cands as $x) {
              if (file_exists($x."wp-settings.php")) { $found = $x; break; }
            }
            // ★ フォールバック：まだ展開されていない場合でも wordpress/ を使う
            if (!$found) {
              $found = $root."/wordpress/";
              if (!is_dir($found)) { mkdir($found, 0777, true); }
              // この時点では wp-settings.php は無くてOK。wp-phpunit が後で取得・配置します。
              fwrite(STDOUT, "[wp-tests-config] fallback to ".$found." (wp-phpunit will install WordPress here)\n");
            }

            $cfg = "<?php\n"
              ."if(!defined(\"ABSPATH\"))define(\"ABSPATH\",\"".$found."\");\n"
              ."if(!defined(\"WP_CONTENT_DIR\"))define(\"WP_CONTENT_DIR\",ABSPATH.\"wp-content\");\n"
              ."if(!defined(\"WP_TESTS_DOMAIN\"))define(\"WP_TESTS_DOMAIN\",\"example.org\");\n"
              ."if(!defined(\"WP_TESTS_EMAIL\"))define(\"WP_TESTS_EMAIL\",\"admin@example.org\");\n"
              ."if(!defined(\"WP_TESTS_TITLE\"))define(\"WP_TESTS_TITLE\",\"Test Site\");\n"
              ."if(!defined(\"WP_PHP_BINARY\"))define(\"WP_PHP_BINARY\",\"php\");\n"
              ."define(\"DB_NAME\",\"wptests\");\n"
              ."define(\"DB_USER\",\"root\");\n"
              ."define(\"DB_PASSWORD\",\"\");\n"
              ."define(\"DB_HOST\",\"localhost\");\n"
              ."define(\"DB_CHARSET\",\"utf8\");\n"
              ."define(\"DB_COLLATE\",\"\");\n"
              ."\$table_prefix=\"wptests_\";\n";
            file_put_contents($root."/wp-tests-config.php", $cfg);
          '

      # （必要に応じて）SQLite ドロップインを配置
      - name: Ensure SQLite drop-in
        run: |
          set -e
          WP_DIR=$(php -r '
            $root = getenv("GITHUB_WORKSPACE") ?: __DIR__;
            $cands = [
              $root."/wordpress/",
              $root."/wp/",
              $root."/vendor/johnpbloch/wordpress-core/wordpress/",
              $root."/vendor/johnpbloch/wordpress-core/",
              $root."/vendor/johnpbloch/wordpress/",
              $root."/vendor/wordpress/wordpress/",
            ];
            foreach ($cands as $x) { if (file_exists($x."wp-settings.php")) { echo $x; exit; } }
            // ★ まだ展開前なら wordpress/ を使う（後で wp-phpunit が中身を入れる）
            echo $root."/wordpress/";
          ')
          echo "WP_DIR=$WP_DIR"
          mkdir -p "${WP_DIR}/wp-content"
          if [ -f vendor/aaemnnosttv/wp-sqlite-db/src/db.php ]; then
            cp -f vendor/aaemnnosttv/wp-sqlite-db/src/db.php "${WP_DIR}/wp-content/db.php"
            echo "Copied SQLite drop-in to ${WP_DIR}/wp-content/db.php"
          else
            echo "aaemnnosttv/wp-sqlite-db not present; skipping copy"
          fi
          mkdir -p tmp && chmod -R 777 tmp

      - name: PHPCS
        run: |
          if [ -x vendor/bin/phpcs ]; then
            set -e
            paths=""
            for d in includes src lib app; do [ -d "$d" ] && paths="$paths $d"; done
            shopt -s nullglob; for f in *.php; do [ "$f" != "wp-tests-config.php" ] && paths="$paths $f"; done
            if [ -z "$(echo "$paths" | tr -d " ")" ]; then echo "No PHP sources to sniff; skipping"; exit 0; fi
            vendor/bin/phpcs \
              --standard=WordPress-Extra \
              --extensions=php \
              --ignore=vendor/*,tests/*,tests/wordpress/*,tmp/*,.github/*,node_modules/*,wp-content/* \
              --warning-severity=0 \
              $paths
          else
            echo "phpcs not installed; skipping"
          fi

      - name: PHPStan
        run: |
          if [ -x vendor/bin/phpstan ]; then
            vendor/bin/phpstan analyse -c phpstan.neon
          else
            echo "phpstan not installed; skipping"
          fi

      - name: PHPUnit
        env:
          WP_PHPUNIT__DIR: ${{ github.workspace }}/vendor/wp-phpunit/wp-phpunit
          WP_PHPUNIT__TESTS_CONFIG: ${{ github.workspace }}/wp-tests-config.php
          WP_PHP_BINARY: php
        run: vendor/bin/phpunit -c phpunit.xml.dist
