name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  php:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: wp
          MYSQL_PASSWORD: wp
          MYSQL_ROOT_PASSWORD: root
        ports: [ "3306:3306" ]
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -p$MYSQL_ROOT_PASSWORD --silent"
          --health-interval=10s --health-timeout=5s --health-retries=10

    env:
      WP_DB_NAME: wordpress_test
      WP_DB_USER: wp
      WP_DB_PASS: wp
      WP_DB_HOST: 127.0.0.1
      WP_PHPUNIT__TESTS_CONFIG: ${{ github.workspace }}/wp-tests-config.php
      WP_TESTS_DIR: ${{ github.workspace }}/vendor/wp-phpunit/wp-phpunit

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          extensions: mysqli

      - name: Install deps
        run: composer install --no-interaction --prefer-dist

      - name: PHP syntax
        run: composer lint

      - name: PHPCS (WordPress-Extra)
        run: vendor/bin/phpcs -q

      - name: PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.neon

      - name: PHPUnit (WP)
        run: vendor/bin/phpunit -c phpunit.xml.dist

      # twentytwentyfour が見つからない場合は、以下を有効化して取得
      # - name: Fetch Twenty Twenty-Four theme
      #   run: |
      #     THEME_DIR="${{ github.workspace }}/vendor/wp-phpunit/wp-phpunit/wordpress/wp-content/themes"
      #     mkdir -p "$THEME_DIR"
      #     curl -L -o /tmp/ttf.zip https://downloads.wordpress.org/theme/twentytwentyfour.latest-stable.zip
      #     unzip -o /tmp/ttf.zip -d "$THEME_DIR"
