name: PHP CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "feature/**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.2' ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
          extensions: mbstring, intl, zip, dom, curl, json, sqlite3

      - name: Configure Composer allow-plugins
        run: |
          composer config --no-plugins allow-plugins.composer/installers true
          composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer config --no-plugins allow-plugins.johnpbloch/wordpress-core-installer true

      - name: Get Composer cache dir
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install deps
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Ensure WPCS standard
        run: composer require wp-coding-standards/wpcs:^3 --no-interaction --prefer-dist || true

      - name: Ensure SQLite driver (composer or fallback)
        run: |
          set -e
          if ! test -f vendor/aaemnnosttv/wp-sqlite-db/src/db.php; then
            composer require aaemnnosttv/wp-sqlite-db:^1.3 --no-interaction --prefer-dist || true
          fi
          if ! test -f vendor/aaemnnosttv/wp-sqlite-db/src/db.php; then
            echo "[fallback] raw fetch"
            mkdir -p vendor/aaemnnosttv/wp-sqlite-db/src
            curl -sSLo vendor/aaemnnosttv/wp-sqlite-db/src/db.php \
              https://raw.githubusercontent.com/aaemnnosttv/wp-sqlite-db/v1.3.2/src/db.php
          fi
          test -f vendor/aaemnnosttv/wp-sqlite-db/src/db.php || (echo "db.php still missing"; exit 1)

      - name: Prepare WP tests (SQLite)
        run: |
          set -e
          mkdir -p tests/wordpress/wp-content
          cp vendor/aaemnnosttv/wp-sqlite-db/src/db.php tests/wordpress/wp-content/db.php
          mkdir -p tmp
          chmod -R 777 tmp

      - name: Create wp-tests-config.php (multi-location)
        run: |
          set -e
          ROOT="$GITHUB_WORKSPACE"
          WP="$ROOT/wordpress"
          write_cfg() {
            path="$1"
            mkdir -p "$(dirname "$path")"
            printf "%s\n" \
              "<?php" \
              "define( 'WP_TESTS_DOMAIN', 'example.org' );" \
              "define( 'WP_TESTS_EMAIL',  'admin@example.org' );" \
              "define( 'WP_TESTS_TITLE',  'Test Site' );" \
              "define( 'WP_PHP_BINARY',   'php' );" \
              "define( 'DB_NAME',     'wptests' );" \
              "define( 'DB_USER',     'root' );" \
              "define( 'DB_PASSWORD', '' );" \
              "define( 'DB_HOST',     'localhost' );" \
              "define( 'DB_CHARSET',  'utf8' );" \
              "define( 'DB_COLLATE',  '' );" \
              "\$table_prefix = 'wptests_';" \
              "define( 'ABSPATH', '${WP}/' );" \
              > "$path"
            echo "wrote $path"
          }
          write_cfg "$ROOT/wp-tests-config.php"
          write_cfg "$ROOT/tests/wp-tests-config.php"
          write_cfg "$ROOT/tests/phpunit/wp-tests-config.php"

      # PHPCS：ソースのみ。ルート直下 *.php は find で wp-tests-config.php を確実に除外
      - name: PHPCS (scoped to source only)
        run: |
          if [ -x vendor/bin/phpcs ]; then
            set -e
            paths=""
            for d in includes src lib app; do [ -d "$d" ] && paths="$paths $d"; done
            # ルート直下の *.php を収集（wp-tests-config.php は除外）
            root_files=$(find . -maxdepth 1 -type f -name '*.php' ! -name 'wp-tests-config.php' -printf '%P\n' | xargs -r echo)
            paths="$paths $root_files"
            # 何もなければスキップ
            if [ -z "$(echo $paths | tr -d ' ')" ]; then echo "No PHP sources to sniff; skipping"; exit 0; fi
            echo "PHPCS targets:$paths"
            vendor/bin/phpcs \
              --standard=WordPress-Extra \
              --extensions=php \
              --ignore=vendor/*,tests/*,tests/wordpress/*,tmp/*,.git/*,.github/*,node_modules/*,wp-content/* \
              --warning-severity=0 \
              $paths
          else
            echo "phpcs not installed; skipping"
          fi

      - name: PHPStan (scoped & CI config)
        run: |
          if [ -x vendor/bin/phpstan ]; then
            set -e
            {
              echo 'parameters:'
              echo '  level: 6'
              echo '  treatPhpDocTypesAsCertain: false'
              echo '  checkMissingIterableValueType: false'
              echo '  paths: []'
              echo '  excludePaths:'
              echo '    analyse:'
              echo '      - vendor/*'
              echo '      - tests/*'
              echo '      - tests/wordpress/*'
              echo '      - tmp/*'
              echo '      - .github/*'
              echo '      - wp-content/*'
              echo '      - node_modules/*'
            } > phpstan-ci.neon
            paths=""
            for d in includes src lib app; do [ -d "$d" ] && paths="$paths $d"; done
            root_files=$(find . -maxdepth 1 -type f -name '*.php' ! -name 'wp-tests-config.php' -printf '%P\n' | xargs -r echo)
            paths="$paths $root_files"
            if [ -z "$(echo $paths | tr -d ' ')" ]; then echo "No PHP sources to analyse; skipping"; exit 0; fi
            echo "PHPStan targets:$paths"
            vendor/bin/phpstan analyse --no-progress --configuration=phpstan-ci.neon $paths
          else
            echo "phpstan not installed; skipping"
          fi

      - name: PHPUnit
        env:
          WP_PHP_BINARY: php
        run: vendor/bin/phpunit -c phpunit.xml.dist
